try:
    from backend.Notebooks.utils import *
    from backend.config import *
except ModuleNotFoundError:
    from Notebooks.utils import *
    from config import *

from fastapi import FastAPI, status, HTTPException
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq
import tensorflow as tf
import numpy as np

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the Groq client with the API key from the environment variable
groq_client = Groq(api_key=groq)

# Load the model
model = load_model()

# Load the tokenizer
tokenizer = load_tokenizer('microsoft/deberta-v3-base')

# Maximum retries for generating a valid Groq response
TOTAL_RETRIES = 3

# Maximum self-improvement cycles
MAX_SELF_IMPROVE_RETRIES = 3


class InputData(BaseModel):
    question: str


def run_groq_pipeline(question: str) -> tuple[str, str] | None:
    """
    Runs the Groq pipeline to generate reasoning and answer for the given question.
    Retries up to TOTAL_RETRIES times if a valid response is not obtained.
    Args:
        question (str): The input question.
    Returns:
        tuple[str, str]: A tuple containing the reasoning and answer if successful, or None if all attempts fail.
    """
    for attempt in range(TOTAL_RETRIES):
        response = generate_reasoning(question, groq_client)
        if response:
            reasoning, answer = extract_reasoning_and_answer(response)
            if answer:
                return reasoning, answer
    return None


def run_critic(question: str, reasoning: str, answer: str) -> tuple[str, list, int]:
    """
    Runs the critic model to evaluate the correctness of the answer based on the question and reasoning.
    args:
        question (str): The input question.
        reasoning (str): The reasoning generated by the Groq pipeline.
        answer (str): The answer generated by the Groq pipeline.
    Returns:
        tuple[str, list, int]: A tuple containing the predicted class label ("Correct" or "Wrong"), the confidence scores, and the predicted class index.
    """
    combined_text = f"INSTRUCTION: {question}\n reasoning: {reasoning}\nRESPONSE: {answer}"

    tokenized_input = tokenizer(
        combined_text,
        padding='max_length',
        truncation=True,
        max_length=512,
        return_tensors='np'
    )

    finalized_input = {
        'token_ids': tf.constant(tokenized_input['input_ids'], dtype=tf.int32),
        'padding_mask': tf.constant(tokenized_input['attention_mask'], dtype=tf.int32),
    }

    prediction = model.predict(finalized_input, verbose=0)
    prediction_class = int(np.argmax(prediction, axis=-1)[0])
    predicted_label = "Correct" if prediction_class == 1 else "Wrong"

    return predicted_label, prediction.tolist(), prediction_class


@app.post("/predict", status_code=status.HTTP_202_ACCEPTED)
async def predict(input_data: InputData):
    """
    Endpoint to handle prediction requests. It takes a question as input, generates reasoning and an answer using the Groq pipeline, and then evaluates the answer using a critic model. The endpoint implements a self-improvement loop that allows for multiple attempts to generate a correct answer based on the critic's feedback.
    Args:
        input_data (InputData): The input data containing the question.
    Returns:
        dict: A dictionary containing the question, response, reasoning, predicted class, critic confidence scores, number of self-improvement attempts, maximum self-improvement retries, and the history of attempts.
    """
    if not input_data.question:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Question is required."
        )

    try:
        reasoning = ""
        answer = ""
        predicted_class = ""
        confidence_scores = []
        self_improve_attempts = 0
        attempts_history = []

        for cycle in range(MAX_SELF_IMPROVE_RETRIES + 1):
            result = run_groq_pipeline(input_data.question)

            if result is None:
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail=f"Failed to generate a valid Groq response after {TOTAL_RETRIES} attempts (cycle {cycle + 1})."
                )

            reasoning, answer = result

            predicted_class, confidence_scores, pred_idx = run_critic(
                input_data.question, reasoning, answer
            )

            attempts_history.append({
                "cycle": cycle + 1,
                "answer": answer,
                "predicted_class": predicted_class,
                "confidence_scores": confidence_scores,
            })


            if predicted_class == "Correct":
                self_improve_attempts = cycle
                break

            if cycle < MAX_SELF_IMPROVE_RETRIES:
                self_improve_attempts = cycle + 1
            else:
                self_improve_attempts = MAX_SELF_IMPROVE_RETRIES

        return {
            "question": input_data.question,
            "response": answer,
            "reasoning": reasoning,
            "predicted_class": predicted_class,
            "critic_confidence_scores": confidence_scores,
            "self_improve_attempts": self_improve_attempts,
            "max_self_improve_retries": MAX_SELF_IMPROVE_RETRIES,
            "attempts_history": attempts_history,
        }

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error during prediction: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred during prediction."
        )